apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: inbox-zero
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
