apiVersion: apps/v1
kind: Deployment
metadata:
  name: activepieces-redis
  namespace: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activepieces-redis
  template:
    metadata:
      labels:
        app: activepieces-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: activepieces-redis-master
  namespace: automation
spec:
  selector:
    app: activepieces-redis  
  ports:
    - port: 6379
      targetPort: 6379
