apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anything-llm-pvc
  namespace: anything-llm
  labels:
    app: anything-llm
spec:
  storageClassName: local-path
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

